import "./globals.css";
import Navbar from "@/components/Navigation/Navbar";

export const metadata = {
  title: "مدرسة عمر بن عبد العزيز - لوحة تحكم",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="ar">
      <body
        className={`flex flex-col min-h-screen max-w-screen-2xl mx-auto`}
      >
        <Navbar />
        <main className="relative overflow-hidden flex-1">{children}</main>
      </body>
    </html>
  );
}
